import type { DriverSpec, RoomConfig } from "./types";
import { extraDrivers } from "./extra-drivers";

export const DEFAULT_CONFIG_PIN = "1234";

export const lgDisplayDriver: DriverSpec = {
  specVersion: "1.0",
  device: { manufacturer: "LG", model: "OLED55C3", type: "display", notes: "IP control demo driver. Simulated by default." },
  transports: {
    lan: { protocol: "tcp", port: 9761, encoding: "ascii", lineEnding: "\r", timeoutMs: 1000 },
    rs232: { baud: 9600, dataBits: 8, parity: "none", stopBits: 1, encoding: "ascii", lineEnding: "\r", timeoutMs: 1000 },
  },
  auth: { type: "none", instanceFields: [] },
  session: { connect: [], keepalive: { payload: null, intervalMs: 0 }, disconnect: [] },
  pacing: { minIntervalMs: 120, powerOnDelayMs: 3000 },
  probe: { transport: "lan", payload: "ka 01 ff", success: { type: "contains", value: "OK" } },
  helpers: { checksum: "none" },
  commands: [
    { id: "power.on", label: "Power On", kind: "action", transport: "lan", payload: "ka 01 01", requires: [], ack: { success: { type: "contains", value: "OK" } } },
    { id: "power.off", label: "Power Off", kind: "action", transport: "lan", payload: "ka 01 00", requires: [], ack: { success: { type: "contains", value: "OK" } } },
    { id: "volume.set", label: "Set Volume", kind: "range", min: 0, max: 100, step: 1, unit: "%", transport: "lan", payload: "kf 01 {value:hex2}", requires: ["power.state=on"], ack: { success: { type: "contains", value: "OK" } } },
    { id: "input.hdmi1", label: "HDMI 1", kind: "action", transport: "lan", payload: "xb 01 90", requires: ["power.state=on"], ack: { success: { type: "contains", value: "OK" } } },
    { id: "input.hdmi2", label: "HDMI 2", kind: "action", transport: "lan", payload: "xb 01 91", requires: ["power.state=on"], ack: { success: { type: "contains", value: "OK" } } },
    { id: "input.usb", label: "USB", kind: "action", transport: "lan", payload: "xb 01 10", requires: ["power.state=on"], ack: { success: { type: "contains", value: "OK" } } },
    { id: "mute.on", label: "Mute", kind: "action", transport: "lan", payload: "ke 01 01", requires: ["power.state=on"], ack: { success: { type: "contains", value: "OK" } } },
    { id: "mute.off", label: "Unmute", kind: "action", transport: "lan", payload: "ke 01 00", requires: ["power.state=on"], ack: { success: { type: "contains", value: "OK" } } },
  ],
  feedback: [
    { id: "power.state", label: "Power", kind: "enum", values: ["off", "on"], transport: "lan", mode: "poll", query: "ka 01 ff", pollMs: 2000, parse: { type: "regex", pattern: "OK([0-9A-Fa-f]+)", map: { "00": "off", "01": "on" } } },
    { id: "volume.level", label: "Volume", kind: "range", min: 0, max: 100, transport: "lan", mode: "poll", query: "kf 01 ff", pollMs: 2000, parse: { type: "regex", pattern: "OK([0-9A-Fa-f]+)" } },
    { id: "input.current", label: "Input", kind: "enum", values: ["hdmi1", "hdmi2", "usb"], transport: "lan", mode: "poll", query: "xb 01 ff", pollMs: 3000, parse: { type: "contains", value: "OK" } },
    { id: "mute.state", label: "Mute", kind: "enum", values: ["off", "on"], transport: "lan", mode: "poll", query: "ke 01 ff", pollMs: 3000, parse: { type: "regex", pattern: "OK([0-9A-Fa-f]+)", map: { "00": "off", "01": "on" } } },
  ],
};

export const ampDriver: DriverSpec = {
  specVersion: "1.0",
  device: { manufacturer: "Generic", model: "LAN-AMP", type: "amplifier", notes: "HTTP JSON demo amplifier." },
  transports: { lan: { protocol: "http", port: 80, timeoutMs: 1500, http: { method: "POST", path: "/api", contentType: "application/json" } } },
  auth: { type: "none", instanceFields: [] },
  pacing: { minIntervalMs: 80, powerOnDelayMs: 800 },
  probe: { transport: "lan", payload: "{\"cmd\":\"ping\"}", success: { type: "contains", value: "ok" } },
  helpers: { checksum: "none" },
  commands: [
    { id: "power.on", label: "Power On", kind: "action", transport: "lan", payload: "{\"cmd\":\"power\",\"value\":\"on\"}" },
    { id: "power.off", label: "Power Off", kind: "action", transport: "lan", payload: "{\"cmd\":\"power\",\"value\":\"off\"}" },
    { id: "volume.set", label: "Set Volume", kind: "range", min: 0, max: 80, step: 1, unit: "dB", transport: "lan", payload: "{\"cmd\":\"volume\",\"value\":{value}}" },
    { id: "source.tv", label: "Source TV", kind: "action", transport: "lan", payload: "{\"cmd\":\"source\",\"value\":\"tv\"}" },
    { id: "source.aux", label: "Source Aux", kind: "action", transport: "lan", payload: "{\"cmd\":\"source\",\"value\":\"aux\"}" },
  ],
  feedback: [
    { id: "power.state", label: "Power", kind: "enum", values: ["off", "on"], transport: "lan", mode: "poll", query: "{\"cmd\":\"power?\"}", pollMs: 2000, parse: { type: "jsonpath", path: "power" } },
    { id: "volume.level", label: "Volume", kind: "range", min: 0, max: 80, transport: "lan", mode: "poll", query: "{\"cmd\":\"volume?\"}", pollMs: 2000, parse: { type: "jsonpath", path: "volume" } },
    { id: "source.current", label: "Source", kind: "enum", values: ["tv", "aux"], transport: "lan", mode: "poll", query: "{\"cmd\":\"source?\"}", pollMs: 3000, parse: { type: "jsonpath", path: "source" } },
  ],
};

export const lightsDriver: DriverSpec = {
  specVersion: "1.0",
  device: { manufacturer: "Generic", model: "RoomLights", type: "lighting" },
  transports: { lan: { protocol: "http", port: 8088, timeoutMs: 1200, http: { method: "PUT", path: "/light", contentType: "application/json" } } },
  auth: { type: "token", instanceFields: ["token"] },
  pacing: { minIntervalMs: 50 },
  probe: { transport: "lan", payload: "{}", success: { type: "contains", value: "ok" } },
  helpers: { checksum: "none" },
  commands: [
    { id: "power.on", label: "Lights On", kind: "action", transport: "lan", payload: "{\"on\":true}" },
    { id: "power.off", label: "Lights Off", kind: "action", transport: "lan", payload: "{\"on\":false}" },
    { id: "level.set", label: "Dimmer", kind: "range", min: 0, max: 100, step: 1, unit: "%", transport: "lan", payload: "{\"bri\":{value}}" },
    { id: "scene.present", label: "Present scene", kind: "action", transport: "lan", payload: "{\"scene\":\"present\"}" },
    { id: "scene.movie", label: "Movie scene", kind: "action", transport: "lan", payload: "{\"scene\":\"movie\"}" },
  ],
  feedback: [
    { id: "power.state", label: "Power", kind: "enum", values: ["off", "on"], transport: "lan", mode: "poll", pollMs: 2500, parse: { type: "jsonpath", path: "on" } },
    { id: "level.value", label: "Level", kind: "range", min: 0, max: 100, transport: "lan", mode: "poll", pollMs: 2500, parse: { type: "jsonpath", path: "bri" } },
    { id: "scene.current", label: "Scene", kind: "enum", values: ["present", "movie", "off"], transport: "lan", mode: "poll", pollMs: 4000, parse: { type: "jsonpath", path: "scene" } },
  ],
};

export const blindsDriver: DriverSpec = {
  specVersion: "1.0",
  device: { manufacturer: "Generic", model: "ShadeBus", type: "shades" },
  transports: { lan: { protocol: "tcp", port: 23, encoding: "ascii", lineEnding: "\r\n", timeoutMs: 1500 } },
  auth: { type: "none" },
  pacing: { minIntervalMs: 200 },
  probe: { transport: "lan", payload: "STATUS", success: { type: "contains", value: "OK" } },
  helpers: { checksum: "none" },
  commands: [
    { id: "position.open", label: "Open", kind: "action", transport: "lan", payload: "OPEN" },
    { id: "position.close", label: "Close", kind: "action", transport: "lan", payload: "CLOSE" },
    { id: "position.set", label: "Set position", kind: "range", min: 0, max: 100, step: 5, unit: "%", transport: "lan", payload: "POS {value}" },
  ],
  feedback: [{ id: "position.level", label: "Position", kind: "range", min: 0, max: 100, transport: "lan", mode: "poll", query: "STATUS", pollMs: 3000, parse: { type: "regex", pattern: "POS=(\\d+)" } }],
};

export const ptzDriver: DriverSpec = {
  specVersion: "1.0",
  device: { manufacturer: "Generic", model: "PTZ-20x", type: "camera" },
  transports: { lan: { protocol: "http", port: 80, timeoutMs: 2000, http: { method: "GET", path: "/cgi-bin/ptz" } } },
  auth: { type: "password", instanceFields: ["user", "password"] },
  pacing: { minIntervalMs: 150 },
  probe: { transport: "lan", payload: "cmd=version", success: { type: "contains", value: "PTZ" } },
  helpers: { checksum: "none" },
  commands: [
    { id: "preset.1", label: "Preset 1", kind: "action", transport: "lan", payload: "cmd=preset&n=1" },
    { id: "preset.2", label: "Preset 2", kind: "action", transport: "lan", payload: "cmd=preset&n=2" },
    { id: "preset.3", label: "Preset 3", kind: "action", transport: "lan", payload: "cmd=preset&n=3" },
    { id: "power.on", label: "Camera On", kind: "action", transport: "lan", payload: "cmd=power&v=on" },
    { id: "power.off", label: "Camera Off", kind: "action", transport: "lan", payload: "cmd=power&v=off" },
  ],
  feedback: [
    { id: "power.state", label: "Power", kind: "enum", values: ["off", "on"], transport: "lan", mode: "poll", pollMs: 4000, parse: { type: "contains", value: "on" } },
    { id: "preset.current", label: "Preset", kind: "enum", values: ["1", "2", "3"], transport: "lan", mode: "poll", pollMs: 4000, parse: { type: "regex", pattern: "preset=(\\d+)" } },
  ],
};

export const samsungQ65tDriver: DriverSpec = {
  specVersion: "2.0",
  device: {
    manufacturer: "Samsung",
    model: "QE50Q65TASXXN",
    type: "display",
    notes: "After full power-off the control socket is dead. Power On sends Wake-on-LAN then KEY_POWERON. Paste the TV MAC in mac. On the TV enable Power On with Mobile / IP Remote. Pairing still needs Allow on screen.",
  },
  transports: {
    lan: {
      protocol: "websocket",
      port: 8001,
      timeoutMs: 8000,
      http: { path: "/api/v2/channels/samsung.remote.control" },
    },
    rs232: { baud: 9600, dataBits: 8, parity: "none", stopBits: 1, encoding: "ascii", lineEnding: "\r", timeoutMs: 1000 },
  },
  auth: {
    type: "token",
    instanceFields: ["token", "name", "mac"],
    pairing: {
      kind: "websocket-handshake",
      ports: [8001, 8002],
      tlsPorts: [8002],
      path: "/api/v2/channels/samsung.remote.control",
      discoverPath: "/api/v2/",
      query: { nameParam: "name", tokenParam: "token", nameFrom: "auth.name" },
      waitContains: "ms.channel.connect",
      commandAck: "none",
      tokenJsonPath: "token",
      userPrompt: "Accept Allow on the TV. If Probe returns a token, save it and use port 8002.",
      steps: [
        { action: "websocket", port: 8001, path: "/api/v2/channels/samsung.remote.control", waitContains: "ms.channel.connect", tokenJsonPath: "token", nextPort: 8002, timeoutMs: 12000 },
        { action: "websocket", port: 8002, tls: true, path: "/api/v2/channels/samsung.remote.control", waitContains: "ms.channel.connect", tokenJsonPath: "token", timeoutMs: 12000 },
      ],
    },
  },
  status: { protocol: "http", port: 8001, path: "/api/v2/" },
  pacing: { minIntervalMs: 250, powerOnDelayMs: 4000 },
  probe: { transport: "lan", payload: "", success: { type: "contains", value: "ms.channel" } },
  helpers: { checksum: "none" },
  commands: [
    { id: "power.on", label: "Power On", kind: "action", transport: "lan", wake: { protocol: "wol" }, payload: "{\"method\":\"ms.remote.control\",\"params\":{\"Cmd\":\"Click\",\"DataOfCmd\":\"KEY_POWERON\",\"Option\":\"false\",\"TypeOfRemote\":\"SendRemoteKey\"}}" },
    { id: "power.off", label: "Power Off", kind: "action", transport: "lan", payload: "{\"method\":\"ms.remote.control\",\"params\":{\"Cmd\":\"Click\",\"DataOfCmd\":\"KEY_POWER\",\"Option\":\"false\",\"TypeOfRemote\":\"SendRemoteKey\"}}" },
    { id: "power.toggle", label: "Power toggle", kind: "action", transport: "lan", payload: "{\"method\":\"ms.remote.control\",\"params\":{\"Cmd\":\"Click\",\"DataOfCmd\":\"KEY_POWER\",\"Option\":\"false\",\"TypeOfRemote\":\"SendRemoteKey\"}}" },
    { id: "volume.up", label: "Volume up", kind: "action", transport: "lan", payload: "{\"method\":\"ms.remote.control\",\"params\":{\"Cmd\":\"Click\",\"DataOfCmd\":\"KEY_VOLUP\",\"Option\":\"false\",\"TypeOfRemote\":\"SendRemoteKey\"}}" },
    { id: "volume.down", label: "Volume down", kind: "action", transport: "lan", payload: "{\"method\":\"ms.remote.control\",\"params\":{\"Cmd\":\"Click\",\"DataOfCmd\":\"KEY_VOLDOWN\",\"Option\":\"false\",\"TypeOfRemote\":\"SendRemoteKey\"}}" },
    { id: "mute.on", label: "Mute", kind: "action", transport: "lan", payload: "{\"method\":\"ms.remote.control\",\"params\":{\"Cmd\":\"Click\",\"DataOfCmd\":\"KEY_MUTE\",\"Option\":\"false\",\"TypeOfRemote\":\"SendRemoteKey\"}}" },
    { id: "mute.off", label: "Unmute", kind: "action", transport: "lan", payload: "{\"method\":\"ms.remote.control\",\"params\":{\"Cmd\":\"Click\",\"DataOfCmd\":\"KEY_MUTE\",\"Option\":\"false\",\"TypeOfRemote\":\"SendRemoteKey\"}}" },
    { id: "ch.up", label: "Channel up", kind: "action", transport: "lan", payload: "{\"method\":\"ms.remote.control\",\"params\":{\"Cmd\":\"Click\",\"DataOfCmd\":\"KEY_CHUP\",\"Option\":\"false\",\"TypeOfRemote\":\"SendRemoteKey\"}}" },
    { id: "ch.down", label: "Channel down", kind: "action", transport: "lan", payload: "{\"method\":\"ms.remote.control\",\"params\":{\"Cmd\":\"Click\",\"DataOfCmd\":\"KEY_CHDOWN\",\"Option\":\"false\",\"TypeOfRemote\":\"SendRemoteKey\"}}" },
    { id: "input.hdmi", label: "HDMI", kind: "action", transport: "lan", payload: "{\"method\":\"ms.remote.control\",\"params\":{\"Cmd\":\"Click\",\"DataOfCmd\":\"KEY_HDMI\",\"Option\":\"false\",\"TypeOfRemote\":\"SendRemoteKey\"}}" },
    { id: "input.hdmi1", label: "HDMI 1", kind: "action", transport: "lan", payload: "{\"method\":\"ms.remote.control\",\"params\":{\"Cmd\":\"Click\",\"DataOfCmd\":\"KEY_HDMI1\",\"Option\":\"false\",\"TypeOfRemote\":\"SendRemoteKey\"}}" },
    { id: "input.hdmi2", label: "HDMI 2", kind: "action", transport: "lan", payload: "{\"method\":\"ms.remote.control\",\"params\":{\"Cmd\":\"Click\",\"DataOfCmd\":\"KEY_HDMI2\",\"Option\":\"false\",\"TypeOfRemote\":\"SendRemoteKey\"}}" },
    { id: "input.hdmi3", label: "HDMI 3", kind: "action", transport: "lan", payload: "{\"method\":\"ms.remote.control\",\"params\":{\"Cmd\":\"Click\",\"DataOfCmd\":\"KEY_HDMI3\",\"Option\":\"false\",\"TypeOfRemote\":\"SendRemoteKey\"}}" },
    { id: "input.source", label: "Source list", kind: "action", transport: "lan", payload: "{\"method\":\"ms.remote.control\",\"params\":{\"Cmd\":\"Click\",\"DataOfCmd\":\"KEY_SOURCE\",\"Option\":\"false\",\"TypeOfRemote\":\"SendRemoteKey\"}}" },
    { id: "input.tv", label: "Live TV", kind: "action", transport: "lan", payload: "{\"method\":\"ms.remote.control\",\"params\":{\"Cmd\":\"Click\",\"DataOfCmd\":\"KEY_TV\",\"Option\":\"false\",\"TypeOfRemote\":\"SendRemoteKey\"}}" },
    { id: "nav.up", label: "Up", kind: "action", transport: "lan", payload: "{\"method\":\"ms.remote.control\",\"params\":{\"Cmd\":\"Click\",\"DataOfCmd\":\"KEY_UP\",\"Option\":\"false\",\"TypeOfRemote\":\"SendRemoteKey\"}}" },
    { id: "nav.down", label: "Down", kind: "action", transport: "lan", payload: "{\"method\":\"ms.remote.control\",\"params\":{\"Cmd\":\"Click\",\"DataOfCmd\":\"KEY_DOWN\",\"Option\":\"false\",\"TypeOfRemote\":\"SendRemoteKey\"}}" },
    { id: "nav.left", label: "Left", kind: "action", transport: "lan", payload: "{\"method\":\"ms.remote.control\",\"params\":{\"Cmd\":\"Click\",\"DataOfCmd\":\"KEY_LEFT\",\"Option\":\"false\",\"TypeOfRemote\":\"SendRemoteKey\"}}" },
    { id: "nav.right", label: "Right", kind: "action", transport: "lan", payload: "{\"method\":\"ms.remote.control\",\"params\":{\"Cmd\":\"Click\",\"DataOfCmd\":\"KEY_RIGHT\",\"Option\":\"false\",\"TypeOfRemote\":\"SendRemoteKey\"}}" },
    { id: "nav.enter", label: "Enter", kind: "action", transport: "lan", payload: "{\"method\":\"ms.remote.control\",\"params\":{\"Cmd\":\"Click\",\"DataOfCmd\":\"KEY_ENTER\",\"Option\":\"false\",\"TypeOfRemote\":\"SendRemoteKey\"}}" },
    { id: "nav.return", label: "Back", kind: "action", transport: "lan", payload: "{\"method\":\"ms.remote.control\",\"params\":{\"Cmd\":\"Click\",\"DataOfCmd\":\"KEY_RETURN\",\"Option\":\"false\",\"TypeOfRemote\":\"SendRemoteKey\"}}" },
    { id: "nav.exit", label: "Exit", kind: "action", transport: "lan", payload: "{\"method\":\"ms.remote.control\",\"params\":{\"Cmd\":\"Click\",\"DataOfCmd\":\"KEY_EXIT\",\"Option\":\"false\",\"TypeOfRemote\":\"SendRemoteKey\"}}" },
    { id: "nav.home", label: "Home / Smart Hub", kind: "action", transport: "lan", payload: "{\"method\":\"ms.remote.control\",\"params\":{\"Cmd\":\"Click\",\"DataOfCmd\":\"KEY_HOME\",\"Option\":\"false\",\"TypeOfRemote\":\"SendRemoteKey\"}}" },
    { id: "nav.menu", label: "Menu", kind: "action", transport: "lan", payload: "{\"method\":\"ms.remote.control\",\"params\":{\"Cmd\":\"Click\",\"DataOfCmd\":\"KEY_MENU\",\"Option\":\"false\",\"TypeOfRemote\":\"SendRemoteKey\"}}" },
    { id: "nav.tools", label: "Tools", kind: "action", transport: "lan", payload: "{\"method\":\"ms.remote.control\",\"params\":{\"Cmd\":\"Click\",\"DataOfCmd\":\"KEY_TOOLS\",\"Option\":\"false\",\"TypeOfRemote\":\"SendRemoteKey\"}}" },
    { id: "nav.info", label: "Info", kind: "action", transport: "lan", payload: "{\"method\":\"ms.remote.control\",\"params\":{\"Cmd\":\"Click\",\"DataOfCmd\":\"KEY_INFO\",\"Option\":\"false\",\"TypeOfRemote\":\"SendRemoteKey\"}}" },
    { id: "nav.guide", label: "Guide", kind: "action", transport: "lan", payload: "{\"method\":\"ms.remote.control\",\"params\":{\"Cmd\":\"Click\",\"DataOfCmd\":\"KEY_GUIDE\",\"Option\":\"false\",\"TypeOfRemote\":\"SendRemoteKey\"}}" },
    { id: "media.play", label: "Play", kind: "action", transport: "lan", payload: "{\"method\":\"ms.remote.control\",\"params\":{\"Cmd\":\"Click\",\"DataOfCmd\":\"KEY_PLAY\",\"Option\":\"false\",\"TypeOfRemote\":\"SendRemoteKey\"}}" },
    { id: "media.pause", label: "Pause", kind: "action", transport: "lan", payload: "{\"method\":\"ms.remote.control\",\"params\":{\"Cmd\":\"Click\",\"DataOfCmd\":\"KEY_PAUSE\",\"Option\":\"false\",\"TypeOfRemote\":\"SendRemoteKey\"}}" },
    { id: "media.stop", label: "Stop", kind: "action", transport: "lan", payload: "{\"method\":\"ms.remote.control\",\"params\":{\"Cmd\":\"Click\",\"DataOfCmd\":\"KEY_STOP\",\"Option\":\"false\",\"TypeOfRemote\":\"SendRemoteKey\"}}" },
    { id: "media.ff", label: "Fast forward", kind: "action", transport: "lan", payload: "{\"method\":\"ms.remote.control\",\"params\":{\"Cmd\":\"Click\",\"DataOfCmd\":\"KEY_FF\",\"Option\":\"false\",\"TypeOfRemote\":\"SendRemoteKey\"}}" },
    { id: "media.rew", label: "Rewind", kind: "action", transport: "lan", payload: "{\"method\":\"ms.remote.control\",\"params\":{\"Cmd\":\"Click\",\"DataOfCmd\":\"KEY_REWIND\",\"Option\":\"false\",\"TypeOfRemote\":\"SendRemoteKey\"}}" },
    { id: "color.red", label: "Red", kind: "action", transport: "lan", payload: "{\"method\":\"ms.remote.control\",\"params\":{\"Cmd\":\"Click\",\"DataOfCmd\":\"KEY_RED\",\"Option\":\"false\",\"TypeOfRemote\":\"SendRemoteKey\"}}" },
    { id: "color.green", label: "Green", kind: "action", transport: "lan", payload: "{\"method\":\"ms.remote.control\",\"params\":{\"Cmd\":\"Click\",\"DataOfCmd\":\"KEY_GREEN\",\"Option\":\"false\",\"TypeOfRemote\":\"SendRemoteKey\"}}" },
    { id: "color.yellow", label: "Yellow", kind: "action", transport: "lan", payload: "{\"method\":\"ms.remote.control\",\"params\":{\"Cmd\":\"Click\",\"DataOfCmd\":\"KEY_YELLOW\",\"Option\":\"false\",\"TypeOfRemote\":\"SendRemoteKey\"}}" },
    { id: "color.blue", label: "Blue", kind: "action", transport: "lan", payload: "{\"method\":\"ms.remote.control\",\"params\":{\"Cmd\":\"Click\",\"DataOfCmd\":\"KEY_BLUE\",\"Option\":\"false\",\"TypeOfRemote\":\"SendRemoteKey\"}}" },
    { id: "digit.0", label: "0", kind: "action", transport: "lan", payload: "{\"method\":\"ms.remote.control\",\"params\":{\"Cmd\":\"Click\",\"DataOfCmd\":\"KEY_0\",\"Option\":\"false\",\"TypeOfRemote\":\"SendRemoteKey\"}}" },
    { id: "digit.1", label: "1", kind: "action", transport: "lan", payload: "{\"method\":\"ms.remote.control\",\"params\":{\"Cmd\":\"Click\",\"DataOfCmd\":\"KEY_1\",\"Option\":\"false\",\"TypeOfRemote\":\"SendRemoteKey\"}}" },
    { id: "digit.2", label: "2", kind: "action", transport: "lan", payload: "{\"method\":\"ms.remote.control\",\"params\":{\"Cmd\":\"Click\",\"DataOfCmd\":\"KEY_2\",\"Option\":\"false\",\"TypeOfRemote\":\"SendRemoteKey\"}}" },
    { id: "digit.3", label: "3", kind: "action", transport: "lan", payload: "{\"method\":\"ms.remote.control\",\"params\":{\"Cmd\":\"Click\",\"DataOfCmd\":\"KEY_3\",\"Option\":\"false\",\"TypeOfRemote\":\"SendRemoteKey\"}}" },
    { id: "digit.4", label: "4", kind: "action", transport: "lan", payload: "{\"method\":\"ms.remote.control\",\"params\":{\"Cmd\":\"Click\",\"DataOfCmd\":\"KEY_4\",\"Option\":\"false\",\"TypeOfRemote\":\"SendRemoteKey\"}}" },
    { id: "digit.5", label: "5", kind: "action", transport: "lan", payload: "{\"method\":\"ms.remote.control\",\"params\":{\"Cmd\":\"Click\",\"DataOfCmd\":\"KEY_5\",\"Option\":\"false\",\"TypeOfRemote\":\"SendRemoteKey\"}}" },
    { id: "digit.6", label: "6", kind: "action", transport: "lan", payload: "{\"method\":\"ms.remote.control\",\"params\":{\"Cmd\":\"Click\",\"DataOfCmd\":\"KEY_6\",\"Option\":\"false\",\"TypeOfRemote\":\"SendRemoteKey\"}}" },
    { id: "digit.7", label: "7", kind: "action", transport: "lan", payload: "{\"method\":\"ms.remote.control\",\"params\":{\"Cmd\":\"Click\",\"DataOfCmd\":\"KEY_7\",\"Option\":\"false\",\"TypeOfRemote\":\"SendRemoteKey\"}}" },
    { id: "digit.8", label: "8", kind: "action", transport: "lan", payload: "{\"method\":\"ms.remote.control\",\"params\":{\"Cmd\":\"Click\",\"DataOfCmd\":\"KEY_8\",\"Option\":\"false\",\"TypeOfRemote\":\"SendRemoteKey\"}}" },
    { id: "digit.9", label: "9", kind: "action", transport: "lan", payload: "{\"method\":\"ms.remote.control\",\"params\":{\"Cmd\":\"Click\",\"DataOfCmd\":\"KEY_9\",\"Option\":\"false\",\"TypeOfRemote\":\"SendRemoteKey\"}}" },
    { id: "app.list", label: "Apps", kind: "action", transport: "lan", payload: "{\"method\":\"ms.remote.control\",\"params\":{\"Cmd\":\"Click\",\"DataOfCmd\":\"KEY_CONTENTS\",\"Option\":\"false\",\"TypeOfRemote\":\"SendRemoteKey\"}}" },
    { id: "app.netflix", label: "Netflix key", kind: "action", transport: "lan", payload: "{\"method\":\"ms.remote.control\",\"params\":{\"Cmd\":\"Click\",\"DataOfCmd\":\"KEY_NETFLIX\",\"Option\":\"false\",\"TypeOfRemote\":\"SendRemoteKey\"}}" },
  ],
  feedback: [
    { id: "power.state", label: "Power", kind: "enum", values: ["off", "on"], transport: "lan", mode: "poll", httpPath: "/api/v2/", pollMs: 8000, parse: { type: "jsonpath", path: "device.PowerState", map: { on: "on", ON: "on", standby: "off", Standby: "off", off: "off" } } },
    { id: "input.current", label: "Input", kind: "string", transport: "lan", mode: "poll", httpPath: "/api/v2/", pollMs: 8000, parse: { type: "jsonpath", path: "device.FrameTVSupport" } },
  ],
};

export const hueBridgeDriver: DriverSpec = {
  specVersion: "1.0",
  device: {
    manufacturer: "Philips",
    model: "Hue Bridge",
    type: "lighting",
    notes: "Press the button on the bridge, then Probe. Save the username token. group 0 = all lights.",
  },
  transports: {
    lan: { protocol: "http", port: 80, timeoutMs: 3000, http: { method: "PUT", path: "/api", contentType: "application/json" } },
  },
  auth: {
    type: "token",
    instanceFields: ["token", "group"],
    pairing: {
      kind: "http-handshake",
      ports: [80, 443],
      path: "/api",
      discoverPath: "/api/config",
      tokenJsonPath: "username",
      userPrompt: "Press the link button on the Hue bridge, then Authenticate. The username token is stored on this card.",
      steps: [
        { action: "http-post", port: 80, path: "/api", body: "{\"devicetype\":\"relay#room\"}", tokenJsonPath: "username", timeoutMs: 8000 },
      ],
    },
  },
  pacing: { minIntervalMs: 80 },
  probe: { transport: "lan", payload: "{\"devicetype\":\"relay#room\"}", success: { type: "contains", value: "username" } },
  helpers: { checksum: "none" },
  inventory: {
    resources: [
      { id: "groups", label: "Groups", httpMethod: "GET", httpPath: "/api/{auth.token}/groups", itemId: "key", itemName: "name", useCommand: "group.on" },
      { id: "scenes", label: "Scenes", httpMethod: "GET", httpPath: "/api/{auth.token}/scenes", itemId: "key", itemName: "name", useCommand: "scene.set" },
      { id: "lights", label: "Lights", httpMethod: "GET", httpPath: "/api/{auth.token}/lights", itemId: "key", itemName: "name", useCommand: "light.on" },
    ],
  },
  commands: [
    { id: "power.on", label: "Lights On", kind: "action", transport: "lan", httpMethod: "PUT", httpPath: "/api/{auth.token}/groups/{auth.group}/action", payload: "{\"on\":true}" },
    { id: "power.off", label: "Lights Off", kind: "action", transport: "lan", httpMethod: "PUT", httpPath: "/api/{auth.token}/groups/{auth.group}/action", payload: "{\"on\":false}" },
    { id: "level.set", label: "Brightness", kind: "range", min: 0, max: 254, step: 1, unit: "bri", transport: "lan", httpMethod: "PUT", httpPath: "/api/{auth.token}/groups/{auth.group}/action", payload: "{\"bri\":{value}}" },
    { id: "scene.set", label: "Recall scene", kind: "enum", transport: "lan", httpMethod: "PUT", httpPath: "/api/{auth.token}/groups/{auth.group}/action", payload: "{\"scene\":\"{value}\"}" },
    { id: "group.on", label: "Group on", kind: "enum", transport: "lan", httpMethod: "PUT", httpPath: "/api/{auth.token}/groups/{value}/action", payload: "{\"on\":true}" },
    { id: "group.off", label: "Group off", kind: "enum", transport: "lan", httpMethod: "PUT", httpPath: "/api/{auth.token}/groups/{value}/action", payload: "{\"on\":false}" },
    { id: "light.on", label: "Light on", kind: "enum", transport: "lan", httpMethod: "PUT", httpPath: "/api/{auth.token}/lights/{value}/state", payload: "{\"on\":true}" },
    { id: "light.off", label: "Light off", kind: "enum", transport: "lan", httpMethod: "PUT", httpPath: "/api/{auth.token}/lights/{value}/state", payload: "{\"on\":false}" },
    { id: "scene.relax", label: "Relax", kind: "action", transport: "lan", httpMethod: "PUT", httpPath: "/api/{auth.token}/groups/{auth.group}/action", payload: "{\"scene\":\"relax\"}" },
    { id: "scene.concentrate", label: "Concentrate", kind: "action", transport: "lan", httpMethod: "PUT", httpPath: "/api/{auth.token}/groups/{auth.group}/action", payload: "{\"scene\":\"concentrate\"}" },
  ],
  feedback: [
    { id: "power.state", label: "Power", kind: "enum", values: ["off", "on"], transport: "lan", mode: "poll", query: "", pollMs: 4000, parse: { type: "contains", value: "on" } },
    { id: "level.value", label: "Level", kind: "range", min: 0, max: 254, transport: "lan", mode: "poll", pollMs: 4000, parse: { type: "jsonpath", path: "bri" } },
  ],
};

export const sonyFhz120lDriver: DriverSpec = {
  specVersion: "1.0",
  device: {
    manufacturer: "Sony",
    model: "VPL-FHZ120L",
    type: "projector",
    notes: "ADCP on TCP 53595. Enable ADCP in the web UI. Turn authentication off for first tests. Warm-up can take a minute after power on.",
  },
  transports: {
    lan: { protocol: "tcp", port: 53595, timeoutMs: 2500, lineEnding: "\r" },
  },
  auth: { type: "none" },
  pacing: { minIntervalMs: 200, powerOnDelayMs: 8000 },
  probe: { transport: "lan", payload: "power_status ?", success: { type: "contains", value: "\"" } },
  helpers: { checksum: "none" },
  commands: [
    { id: "power.on", label: "Power On", kind: "action", transport: "lan", payload: "power \"on\"" },
    { id: "power.off", label: "Power Off", kind: "action", transport: "lan", payload: "power \"off\"" },
    { id: "input.hdmi", label: "HDMI", kind: "action", transport: "lan", payload: "input \"hdmi\"", requires: ["power.state=on"] },
    { id: "input.dvi", label: "DVI-D", kind: "action", transport: "lan", payload: "input \"dvi\"", requires: ["power.state=on"] },
    { id: "input.hdbaset", label: "HDBaseT", kind: "action", transport: "lan", payload: "input \"hdbaset\"", requires: ["power.state=on"] },
    { id: "input.rgb", label: "Input A", kind: "action", transport: "lan", payload: "input \"rgb\"", requires: ["power.state=on"] },
    { id: "mute.on", label: "Blank On", kind: "action", transport: "lan", payload: "blank \"on\"", requires: ["power.state=on"] },
    { id: "mute.off", label: "Blank Off", kind: "action", transport: "lan", payload: "blank \"off\"", requires: ["power.state=on"] },
  ],
  feedback: [
    { id: "power.state", label: "Power", kind: "enum", values: ["off", "on"], transport: "lan", mode: "poll", query: "power_status ?", pollMs: 4000, parse: { type: "contains", value: "on" } },
    { id: "input.current", label: "Input", kind: "string", transport: "lan", mode: "poll", query: "input ?", pollMs: 4000, parse: { type: "regex", pattern: "\"([^\"]+)\"" } },
  ],
};

export const relayHostDriver: DriverSpec = {
  specVersion: "2.0",
  device: { manufacturer: "Relay", model: "Host", type: "host", notes: "This Pi or another Relay on the LAN. Localhost = this machine. Other IP + port 8081 + PIN = that room." },
  transports: { lan: { protocol: "http", port: 8081, timeoutMs: 4000 } },
  auth: { type: "pin", instanceFields: ["pin", "secret"] },
  pacing: { minIntervalMs: 0, powerOnDelayMs: 0 },
  probe: { transport: "lan", payload: "", success: { type: "contains", value: "" } },
  helpers: { checksum: "none" },
  inventory: {
    resources: [
      { id: "vars", label: "Variables", httpMethod: "GET", httpPath: "/api/vars", itemId: "key", itemName: "name", useCommand: "var.set" },
      { id: "macros", label: "Macros", httpMethod: "GET", httpPath: "/api/room", itemId: "key", itemName: "label", useCommand: "macro.run" },
    ],
  },
  commands: [
    { id: "display.dim", label: "Dim panel", kind: "action", transport: "lan", payload: "dim" },
    { id: "display.wake", label: "Wake panel", kind: "action", transport: "lan", payload: "wake" },
    { id: "display.fullscreen", label: "Panel fullscreen", kind: "action", transport: "lan", payload: "fullscreen" },
    { id: "panel.lock", label: "Lock panel", kind: "action", transport: "lan", payload: "lock" },
    { id: "panel.unlock", label: "Unlock panel", kind: "action", transport: "lan", payload: "unlock" },
    { id: "ui.toast", label: "Show message", kind: "enum", transport: "lan", payload: "{value}", values: [] },
    { id: "ui.block", label: "Block UI", kind: "enum", transport: "lan", payload: "{value}", values: [] },
    { id: "ui.unblock", label: "Unblock UI", kind: "action", transport: "lan", payload: "unblock" },
    { id: "ui.clear", label: "Clear messages", kind: "action", transport: "lan", payload: "clear" },
    { id: "ui.page", label: "Go to page", kind: "enum", transport: "lan", payload: "{value}", values: [] },
    { id: "system.restart", label: "Restart Relay", kind: "action", transport: "lan", payload: "restart" },
    { id: "system.update", label: "Update Relay", kind: "action", transport: "lan", payload: "update" },
    { id: "system.reboot", label: "Reboot machine", kind: "action", transport: "lan", payload: "reboot" },
    { id: "var.get", label: "Read variable", kind: "enum", transport: "lan", payload: "{value}" },
    { id: "var.set", label: "Write variable", kind: "enum", transport: "lan", payload: "{value}" },
    { id: "macro.run", label: "Run macro", kind: "enum", transport: "lan", payload: "{value}" },
  ],
  feedback: [
    { id: "system.uptime", label: "OS uptime (s)", kind: "range", transport: "lan", mode: "poll", query: "uptime", pollMs: 5000, parse: { type: "exact" } },
    { id: "relay.uptime", label: "Relay uptime (s)", kind: "range", transport: "lan", mode: "poll", query: "relay-uptime", pollMs: 5000, parse: { type: "exact" } },
    { id: "system.temp", label: "CPU temp °C", kind: "range", transport: "lan", mode: "poll", query: "temp", pollMs: 5000, parse: { type: "exact" } },
    { id: "system.memory", label: "Free RAM MB", kind: "range", transport: "lan", mode: "poll", query: "mem", pollMs: 5000, parse: { type: "exact" } },
    { id: "system.load", label: "Load", kind: "range", transport: "lan", mode: "poll", query: "load", pollMs: 5000, parse: { type: "exact" } },
    { id: "system.version", label: "Version", kind: "string", transport: "lan", mode: "poll", query: "version", pollMs: 30000, parse: { type: "exact" } },
    { id: "system.platform", label: "Platform", kind: "string", transport: "lan", mode: "poll", query: "platform", pollMs: 30000, parse: { type: "exact" } },
    { id: "panel.locked", label: "Panel lock", kind: "toggle", transport: "lan", mode: "poll", query: "lock", pollMs: 2000, parse: { type: "exact" } },
    { id: "display.dimmed", label: "Panel dim", kind: "toggle", transport: "lan", mode: "poll", query: "dim", pollMs: 2000, parse: { type: "exact" } },
  ],
};

export const bundledDrivers: Record<string, DriverSpec> = {
  "relay-host.json": relayHostDriver,
  "lg-oled55c3.json": lgDisplayDriver,
  "samsung-qe50q65t.json": samsungQ65tDriver,
  "philips-hue-bridge.json": hueBridgeDriver,
  "sony-vpl-fhz120l.json": sonyFhz120lDriver,
  "lan-amp.json": ampDriver,
  "room-lights.json": lightsDriver,
  "shade-bus.json": blindsDriver,
  "ptz-20x.json": ptzDriver,
  ...extraDrivers,
};

export function defaultRoomConfig(): RoomConfig {
  return {
    configVersion: "1.0",
    exportedAt: null,
    sourceRoomId: null,
    room: {
      id: "room-a",
      name: "Conference A",
      panelAccess: "open",
      panelPin: null,
      configPin: DEFAULT_CONFIG_PIN,
      externalControl: true,
      theme: "dark",
      idleDimSeconds: 90,
      keepAwake: true,
      panelFullscreen: false,
      grid: { cols: 6, rows: 8 },
      network: { mode: "dhcp", address: "10.0.10.10", prefix: 24, gateway: "10.0.10.1", dns: "10.0.10.1", ntp: "", timezone: "system", hostname: "relay-room-a" },
    },
    devices: [
      { id: "host", name: "Relay", driver: "relay-host.json", transport: "lan", host: "localhost", auth: {}, enabledFeatures: [], simulate: false },
      { id: "tv", name: "Display", driver: "lg-oled55c3.json", transport: "lan", host: "10.0.10.21", auth: {}, enabledFeatures: ["power.on", "power.off", "volume.set", "input.hdmi1", "input.hdmi2", "input.usb", "power.state", "volume.level", "input.current"], simulate: true },
      { id: "amp", name: "Amplifier", driver: "lan-amp.json", transport: "lan", host: "10.0.10.22", auth: {}, enabledFeatures: ["power.on", "power.off", "volume.set", "source.tv", "source.aux", "power.state", "volume.level", "source.current"], simulate: true },
      { id: "lights", name: "Lights", driver: "room-lights.json", transport: "lan", host: "10.0.10.30", auth: {}, enabledFeatures: ["power.on", "power.off", "level.set", "scene.present", "scene.movie", "power.state", "level.value", "scene.current"], simulate: true },
      { id: "blinds", name: "Blinds", driver: "shade-bus.json", transport: "lan", host: "10.0.10.31", auth: {}, enabledFeatures: ["position.open", "position.close", "position.set", "position.level"], simulate: true },
      { id: "cam", name: "Camera", driver: "ptz-20x.json", transport: "lan", host: "10.0.10.40", auth: {}, enabledFeatures: ["preset.1", "preset.2", "preset.3", "power.on", "power.off", "power.state", "preset.current"], simulate: true },
    ],
    pages: [
      {
        id: "home",
        label: "Home",
        grid: { cols: 6, rows: 8 },
        widgets: [
          { id: "w-watch", type: "button", x: 0, y: 0, w: 2, h: 2, label: "Watch", color: "steel", icon: "tv", confirm: false, highlight: "latch", latchGroup: "scene", bind: { kind: "macro", id: "watch-tv" } },
          { id: "w-present", type: "button", x: 2, y: 0, w: 2, h: 2, label: "Present", color: "sage", icon: "presentation", confirm: false, highlight: "latch", latchGroup: "scene", bind: { kind: "macro", id: "present" } },
          { id: "w-off", type: "button", x: 4, y: 0, w: 2, h: 2, label: "All Off", color: "clay", icon: "power", confirm: true, highlight: "latch", latchGroup: "scene", bind: { kind: "macro", id: "all-off" } },
          { id: "w-tv-pwr", type: "status", x: 0, y: 2, w: 3, h: 1, label: "Display", color: "fog", icon: "monitor", bind: { kind: "variable", variable: "tvPower" } },
          { id: "w-scene", type: "status", x: 3, y: 2, w: 3, h: 1, label: "Scene", color: "fog", bind: { kind: "variable", variable: "scene" } },
          { id: "w-vol", type: "slider", x: 0, y: 3, w: 6, h: 1, label: "Volume", color: "steel", latchGroup: "scene", enableWhen: { variable: "tvPower", equals: "on" }, min: "{volMin}", max: "{volMax}", bind: { kind: "range", device: "tv", command: "volume.set", feedback: "volume.level", variable: "watchVol" } },
          { id: "w-lights", type: "slider", x: 0, y: 4, w: 6, h: 1, label: "Lights", color: "sage", bind: { kind: "range", device: "lights", command: "level.set", feedback: "level.value" } },
          { id: "w-blinds", type: "slider", x: 0, y: 5, w: 6, h: 1, label: "Blinds", color: "fog", bind: { kind: "range", device: "blinds", command: "position.set", feedback: "position.level" } },
          { id: "w-src", type: "button", x: 0, y: 6, w: 2, h: 2, label: "Sources", color: "ink", icon: "waypoints", bind: { kind: "macro", id: "open-sources", gotoPage: "sources" } },
          { id: "w-cam", type: "button", x: 2, y: 6, w: 2, h: 2, label: "Camera", color: "ink", icon: "video", bind: { kind: "macro", id: "open-camera", gotoPage: "camera" } },
          { id: "w-sys", type: "button", x: 4, y: 6, w: 2, h: 2, label: "Room", color: "ink", bind: { kind: "macro", id: "open-room", gotoPage: "room" } },
        ],
      },
      {
        id: "sources",
        label: "Sources",
        grid: { cols: 6, rows: 6 },
        widgets: [
          { id: "s-home", type: "button", x: 0, y: 0, w: 2, h: 1, label: "Home", color: "ink", icon: "house", bind: { kind: "macro", id: "open-home", gotoPage: "home" } },
          { id: "s-title", type: "label", x: 2, y: 0, w: 4, h: 1, label: "Inputs", color: "fog", bind: { kind: "macro", id: "open-sources" } },
          { id: "s-hdmi1", type: "button", x: 0, y: 1, w: 3, h: 2, label: "HDMI 1", color: "ocean", icon: "hdmi", highlight: "latch", latchGroup: "input", enableWhen: { variable: "tvPower", equals: "on" }, bind: { kind: "macro", id: "input-hdmi1" } },
          { id: "s-hdmi2", type: "button", x: 3, y: 1, w: 3, h: 2, label: "HDMI 2", color: "ocean", icon: "hdmi", highlight: "latch", latchGroup: "input", enableWhen: { variable: "tvPower", equals: "on" }, bind: { kind: "macro", id: "input-hdmi2" } },
          { id: "s-usb", type: "button", x: 0, y: 3, w: 3, h: 2, label: "USB", color: "slate", highlight: "latch", latchGroup: "input", bind: { kind: "macro", id: "input-usb" } },
          { id: "s-aux", type: "button", x: 3, y: 3, w: 3, h: 2, label: "Amp Aux", color: "pine", highlight: "latch", latchGroup: "input", bind: { kind: "macro", id: "source-aux" } },
        ],
      },
      {
        id: "camera",
        label: "Camera",
        grid: { cols: 6, rows: 6 },
        widgets: [
          { id: "c-home", type: "button", x: 0, y: 0, w: 2, h: 1, label: "Home", color: "ink", icon: "house", bind: { kind: "macro", id: "open-home", gotoPage: "home" } },
          { id: "c-st", type: "status", x: 2, y: 0, w: 4, h: 1, label: "Preset", color: "fog", bind: { kind: "variable", variable: "camPreset" } },
          { id: "c-p1", type: "button", x: 0, y: 1, w: 2, h: 2, label: "Desk", color: "ocean", icon: "user", highlight: "latch", latchGroup: "cam", bind: { kind: "macro", id: "cam-desk" } },
          { id: "c-p2", type: "button", x: 2, y: 1, w: 2, h: 2, label: "Board", color: "ocean", icon: "users", highlight: "latch", latchGroup: "cam", bind: { kind: "macro", id: "cam-board" } },
          { id: "c-p3", type: "button", x: 4, y: 1, w: 2, h: 2, label: "Wide", color: "ocean", icon: "scan", highlight: "latch", latchGroup: "cam", bind: { kind: "macro", id: "cam-wide" } },
          { id: "c-on", type: "button", x: 0, y: 3, w: 3, h: 2, label: "Camera On", color: "pine", bind: { kind: "macro", id: "cam-on" } },
          { id: "c-off", type: "button", x: 3, y: 3, w: 3, h: 2, label: "Camera Off", color: "clay", confirm: true, bind: { kind: "macro", id: "cam-off" } },
        ],
      },
      {
        id: "room",
        label: "Room",
        grid: { cols: 6, rows: 6 },
        widgets: [
          { id: "r-home", type: "button", x: 0, y: 0, w: 2, h: 1, label: "Home", color: "ink", bind: { kind: "macro", id: "open-home", gotoPage: "home" } },
          { id: "r-title", type: "label", x: 2, y: 0, w: 4, h: 1, label: "This panel", color: "fog", bind: { kind: "macro", id: "open-room" } },
          { id: "r-msg", type: "button", x: 0, y: 1, w: 3, h: 2, label: "Message", color: "steel", bind: { kind: "macro", id: "announce" } },
          { id: "r-hold", type: "button", x: 3, y: 1, w: 3, h: 2, label: "Hold", color: "clay", bind: { kind: "macro", id: "hold" } },
          { id: "r-dim", type: "button", x: 0, y: 3, w: 2, h: 2, label: "Dim", color: "fog", bind: { kind: "macro", id: "dim-panel" } },
          { id: "r-lock", type: "button", x: 2, y: 3, w: 2, h: 2, label: "Lock", color: "ink", bind: { kind: "macro", id: "lock-panel" } },
          { id: "r-wake", type: "button", x: 4, y: 3, w: 2, h: 2, label: "Wake", color: "sage", bind: { kind: "macro", id: "wake-panel" } },
        ],
      },
    ],
    macros: [
      { id: "power-av", label: "Power AV", retries: 1, onFail: { kind: "none" }, steps: [
        { device: "tv", command: "power.on", skipIf: { feedback: "power.state", equals: "on" }, delayMsAfter: 400 },
        { device: "amp", command: "power.on", skipIf: { feedback: "power.state", equals: "on" }, delayMsAfter: 200 },
      ] },
      { id: "watch-tv", label: "Watch TV", retries: 2, onFail: { kind: "none" }, steps: [
        { setVar: "scene", value: "watch" },
        { device: "host", command: "ui.block", value: "Starting Watch" },
        { macroId: "power-av", delayMsAfter: 100 },
        { device: "tv", command: "input.hdmi1", delayMsAfter: 150 },
        { device: "amp", command: "source.tv", delayMsAfter: 80 },
        { device: "tv", command: "volume.set", value: "{watchVol}", delayMsAfter: 80 },
        { device: "lights", command: "scene.movie", delayMsAfter: 80 },
        { device: "blinds", command: "position.set", value: 20, delayMsAfter: 80 },
        { device: "host", command: "ui.unblock" },
      ] },
      { id: "present", label: "Present", retries: 2, onFail: { kind: "none" }, steps: [
        { setVar: "scene", value: "present" },
        { device: "host", command: "ui.block", value: "Starting Present" },
        { macroId: "power-av", delayMsAfter: 100 },
        { device: "tv", command: "input.hdmi2", delayMsAfter: 150 },
        { device: "tv", command: "volume.set", value: "{presentVol}", delayMsAfter: 80 },
        { device: "lights", command: "scene.present", delayMsAfter: 80 },
        { device: "blinds", command: "position.open", delayMsAfter: 80 },
        { macroId: "cam-board", delayMsAfter: 80 },
        { device: "host", command: "ui.unblock" },
      ] },
      { id: "all-off", label: "All Off", retries: 1, onFail: { kind: "none" }, steps: [
        { setVar: "scene", value: "off" },
        { device: "host", command: "ui.block", value: "Powering down" },
        { device: "tv", command: "power.off", delayMsAfter: 120 },
        { device: "amp", command: "power.off", delayMsAfter: 120 },
        { device: "cam", command: "power.off", delayMsAfter: 120 },
        { device: "lights", command: "power.off", delayMsAfter: 80 },
        { device: "blinds", command: "position.close", delayMsAfter: 80 },
        { device: "host", command: "ui.unblock" },
      ] },
      { id: "announce", label: "Message", retries: 0, onFail: { kind: "none" }, steps: [
        { device: "host", command: "ui.toast", value: "Conference A is ready" },
      ] },
      { id: "hold", label: "Hold", retries: 0, onFail: { kind: "none" }, steps: [
        { device: "host", command: "ui.block", value: "Please wait", delayMsAfter: 2500 },
        { device: "host", command: "ui.unblock" },
      ] },
      { id: "dim-panel", label: "Dim panel", retries: 0, onFail: { kind: "none" }, steps: [{ device: "host", command: "display.dim" }] },
      { id: "wake-panel", label: "Wake panel", retries: 0, onFail: { kind: "none" }, steps: [{ device: "host", command: "display.wake" }] },
      { id: "lock-panel", label: "Lock panel", retries: 0, onFail: { kind: "none" }, steps: [{ device: "host", command: "panel.lock" }] },
      { id: "open-home", label: "Open Home", retries: 0, onFail: { kind: "none" }, steps: [] },
      { id: "open-sources", label: "Open Sources", retries: 0, onFail: { kind: "none" }, steps: [] },
      { id: "open-camera", label: "Open Camera", retries: 0, onFail: { kind: "none" }, steps: [] },
      { id: "open-room", label: "Open Room", retries: 0, onFail: { kind: "none" }, steps: [] },
      { id: "input-hdmi1", label: "HDMI 1", retries: 1, onFail: { kind: "none" }, steps: [{ device: "tv", command: "input.hdmi1" }] },
      { id: "input-hdmi2", label: "HDMI 2", retries: 1, onFail: { kind: "none" }, steps: [{ device: "tv", command: "input.hdmi2" }] },
      { id: "input-usb", label: "USB", retries: 1, onFail: { kind: "none" }, steps: [{ device: "tv", command: "input.usb" }] },
      { id: "source-aux", label: "Amp Aux", retries: 1, onFail: { kind: "none" }, steps: [{ device: "amp", command: "source.aux" }] },
      { id: "cam-desk", label: "Camera Desk", retries: 1, onFail: { kind: "none" }, steps: [{ device: "cam", command: "preset.1" }, { setVar: "camPreset", value: "1" }] },
      { id: "cam-board", label: "Camera Board", retries: 1, onFail: { kind: "none" }, steps: [{ device: "cam", command: "power.on", delayMsAfter: 80 }, { device: "cam", command: "preset.2" }, { setVar: "camPreset", value: "2" }] },
      { id: "cam-wide", label: "Camera Wide", retries: 1, onFail: { kind: "none" }, steps: [{ device: "cam", command: "preset.3" }, { setVar: "camPreset", value: "3" }] },
      { id: "cam-on", label: "Camera On", retries: 1, onFail: { kind: "none" }, steps: [{ device: "cam", command: "power.on" }] },
      { id: "cam-off", label: "Camera Off", retries: 1, onFail: { kind: "none" }, steps: [{ device: "cam", command: "power.off" }] },
    ],
    variables: [
      { id: "volMin", label: "Volume min", kind: "number", default: 0, min: 0, max: 100, step: 1 },
      { id: "volMax", label: "Volume max", kind: "number", default: 40, min: 0, max: 100, step: 1 },
      { id: "watchVol", label: "Watch volume", kind: "number", default: 22, min: 0, max: 100, step: 1, pushDevice: "tv", pushCommand: "volume.set" },
      { id: "presentVol", label: "Present volume", kind: "number", default: 18, min: 0, max: 100, step: 1 },
      { id: "tvPower", label: "Display power", kind: "enum", default: "off", values: ["off", "on"] },
      { id: "ampPower", label: "Amp power", kind: "enum", default: "off", values: ["off", "on"] },
      { id: "camPreset", label: "Camera preset", kind: "enum", default: "1", values: ["1", "2", "3"] },
      { id: "scene", label: "Scene", kind: "text", default: "idle" },
    ],
    schedules: [{ id: "weekday-off", label: "Weeknight all off", enabled: false, time: "22:00", days: [1, 2, 3, 4, 5], macroId: "all-off" }],
    monitors: [
      { id: "mon-tv-power", label: "Display power", enabled: true, device: "tv", feedback: "power.state", pollMs: 4000, writeVar: "tvPower", mapMode: "raw", map: [] },
      { id: "mon-amp-power", label: "Amp power", enabled: true, device: "amp", feedback: "power.state", pollMs: 4000, writeVar: "ampPower", mapMode: "raw", map: [] },
      { id: "mon-cam-preset", label: "Camera preset", enabled: true, device: "cam", feedback: "preset.current", pollMs: 5000, writeVar: "camPreset", mapMode: "raw", map: [] },
    ],
    triggers: [
      { id: "tr-loud", label: "Volume warning", enabled: false, variable: "watchVol", compare: "gt", equals: "35", mode: "change", intervalSec: 1, delaySec: 0, holdSec: 0, macroId: "announce" },
    ],
    interfaces: [],
  };
}

export function emptyRoomConfig(pin = DEFAULT_CONFIG_PIN): RoomConfig {
  const demo = defaultRoomConfig();
  return {
    configVersion: "1.0",
    exportedAt: null,
    sourceRoomId: null,
    room: { ...demo.room, id: "room", name: "New room", panelAccess: "open", panelPin: null, configPin: pin },
    devices: [],
    pages: [{ id: "home", label: "Home", grid: { ...demo.room.grid }, widgets: [] }],
    macros: [],
    variables: [],
    schedules: [],
    monitors: [],
    triggers: [],
    interfaces: [],
  };
}

export function defaultDeviceState(): Record<string, Record<string, string | number | boolean>> {
  return {
    tv: { "power.state": "off", "volume.level": 18, "input.current": "hdmi1", "mute.state": "off" },
    amp: { "power.state": "off", "volume.level": 30, "source.current": "tv" },
    lights: { "power.state": "on", "level.value": 70, "scene.current": "present" },
    blinds: { "position.level": 40 },
    cam: { "power.state": "off", "preset.current": "1" },
  };
}
