import type { DriverSpec } from "./types";

export const extraDrivers: Record<string, DriverSpec> = {
  "google-chromecast.json": {
    specVersion: "1.0",
    device: { manufacturer: "Google", model: "Chromecast", type: "source", notes: "Cast on TCP 8009. Volume uses valueMap 0–100 → 0–1." },
    transports: { lan: { protocol: "cast", port: 8009, timeoutMs: 5000 } },
    auth: { type: "none" },
    pacing: { minIntervalMs: 250 },
    probe: { transport: "lan", payload: "{\"type\":\"GET_STATUS\",\"requestId\":1}", success: { type: "contains", value: "status" } },
    helpers: { checksum: "none" },
    commands: [
      { id: "status.get", label: "Status", kind: "action", transport: "lan", payload: "{\"type\":\"GET_STATUS\",\"requestId\":1}" },
      { id: "power.off", label: "Stop / idle", kind: "action", transport: "lan", payload: "{\"type\":\"STOP\",\"requestId\":2}" },
      { id: "mute.on", label: "Mute", kind: "action", transport: "lan", payload: "{\"type\":\"SET_VOLUME\",\"requestId\":3,\"volume\":{\"muted\":true}}" },
      { id: "mute.off", label: "Unmute", kind: "action", transport: "lan", payload: "{\"type\":\"SET_VOLUME\",\"requestId\":4,\"volume\":{\"muted\":false}}" },
      { id: "volume.set", label: "Volume", kind: "range", min: 0, max: 100, step: 1, transport: "lan", valueMap: { kind: "float", inMin: 0, inMax: 100, outMin: 0, outMax: 1, decimals: 3 }, payload: "{\"type\":\"SET_VOLUME\",\"requestId\":5,\"volume\":{\"level\":{value}}}" },
      { id: "app.youtube", label: "YouTube", kind: "action", transport: "lan", payload: "{\"type\":\"LAUNCH\",\"requestId\":6,\"appId\":\"233637DE\"}" },
      { id: "app.netflix", label: "Netflix", kind: "action", transport: "lan", payload: "{\"type\":\"LAUNCH\",\"requestId\":7,\"appId\":\"CA5E8412\"}" },
      { id: "app.spotify", label: "Spotify", kind: "action", transport: "lan", payload: "{\"type\":\"LAUNCH\",\"requestId\":8,\"appId\":\"CC32E753\"}" },
      { id: "app.backdrop", label: "Backdrop", kind: "action", transport: "lan", payload: "{\"type\":\"LAUNCH\",\"requestId\":9,\"appId\":\"E8C28D3C\"}" },
      { id: "media.play", label: "Play", kind: "action", transport: "lan", namespace: "urn:x-cast:com.google.cast.media", payload: "{\"type\":\"PLAY\",\"mediaSessionId\":1,\"requestId\":10}" },
      { id: "media.pause", label: "Pause", kind: "action", transport: "lan", namespace: "urn:x-cast:com.google.cast.media", payload: "{\"type\":\"PAUSE\",\"mediaSessionId\":1,\"requestId\":11}" },
      { id: "media.stop", label: "Stop", kind: "action", transport: "lan", namespace: "urn:x-cast:com.google.cast.media", payload: "{\"type\":\"STOP\",\"mediaSessionId\":1,\"requestId\":12}" },
      { id: "media.next", label: "Next", kind: "action", transport: "lan", namespace: "urn:x-cast:com.google.cast.media", payload: "{\"type\":\"QUEUE_NEXT\",\"mediaSessionId\":1,\"requestId\":13}" },
      { id: "media.prev", label: "Previous", kind: "action", transport: "lan", namespace: "urn:x-cast:com.google.cast.media", payload: "{\"type\":\"QUEUE_PREV\",\"mediaSessionId\":1,\"requestId\":14}" },
    ],
    feedback: [
      { id: "status.raw", label: "Status", kind: "string", transport: "lan", mode: "poll", query: "{\"type\":\"GET_STATUS\",\"requestId\":1}", pollMs: 8000, parse: { type: "jsonpath", path: "type" } },
      { id: "volume.level", label: "Volume", kind: "range", min: 0, max: 1, transport: "lan", mode: "poll", query: "{\"type\":\"GET_STATUS\",\"requestId\":1}", pollMs: 8000, parse: { type: "jsonpath", path: "status.volume.level" } },
      { id: "app.current", label: "App", kind: "string", transport: "lan", mode: "poll", query: "{\"type\":\"GET_STATUS\",\"requestId\":1}", pollMs: 8000, parse: { type: "jsonpath", path: "status.applications.0.displayName" } },
    ],
  },
  "pjlink-projector.json": {
    specVersion: "1.0",
    device: { manufacturer: "Generic", model: "PJLink Class 1", type: "projector", notes: "TCP 4352. Password in auth.password if PJLINK 1." },
    transports: { lan: { protocol: "pjlink", port: 4352, timeoutMs: 2500 } },
    auth: { type: "password", instanceFields: ["password"] },
    pacing: { minIntervalMs: 200, powerOnDelayMs: 8000 },
    probe: { transport: "lan", payload: "%1POWR ?", success: { type: "contains", value: "POWR" } },
    helpers: { checksum: "none" },
    commands: [
      { id: "power.on", label: "Power On", kind: "action", transport: "lan", payload: "%1POWR 1" },
      { id: "power.off", label: "Power Off", kind: "action", transport: "lan", payload: "%1POWR 0" },
      { id: "mute.on", label: "AV Mute", kind: "action", transport: "lan", payload: "%1AVMT 31" },
      { id: "mute.off", label: "AV Mute Off", kind: "action", transport: "lan", payload: "%1AVMT 30" },
      { id: "input.hdmi1", label: "HDMI 1", kind: "action", transport: "lan", payload: "%1INPT 32" },
      { id: "input.hdmi2", label: "HDMI 2", kind: "action", transport: "lan", payload: "%1INPT 33" },
    ],
    feedback: [
      { id: "power.state", label: "Power", kind: "enum", values: ["off", "on"], transport: "lan", mode: "poll", query: "%1POWR ?", pollMs: 4000, parse: { type: "contains", value: "=1" } },
    ],
  },
  "wake-on-lan.json": {
    specVersion: "1.0",
    device: { manufacturer: "Generic", model: "Wake-on-LAN", type: "other", notes: "MAC in auth.mac." },
    transports: { lan: { protocol: "wol", port: 9, timeoutMs: 1000 } },
    auth: { type: "none", instanceFields: ["mac"] },
    helpers: { checksum: "none" },
    commands: [{ id: "power.on", label: "Wake", kind: "action", transport: "lan", payload: "" }],
    feedback: [],
  },
  "pi-gpio.json": {
    specVersion: "1.0",
    device: { manufacturer: "Raspberry Pi", model: "GPIO line", type: "other", notes: "Line number in Port. Chip gpiochip0." },
    transports: { local: { kind: "gpio", chip: "gpiochip0", timeoutMs: 1500 } },
    auth: { type: "none", instanceFields: ["pin"] },
    helpers: { checksum: "none" },
    commands: [
      { id: "power.on", label: "High", kind: "action", transport: "rs232", payload: "1" },
      { id: "power.off", label: "Low", kind: "action", transport: "rs232", payload: "0" },
    ],
    feedback: [],
  },
  "local-serial.json": {
    specVersion: "1.0",
    device: { manufacturer: "Generic", model: "Serial / COM", type: "other", notes: "Set Interface to COM1 / /dev/ttyUSB0." },
    transports: {
      local: { kind: "serial", path: "COM3", baud: 9600, timeoutMs: 1500 },
      rs232: { baud: 9600, dataBits: 8, parity: "none", stopBits: 1, lineEnding: "\r", timeoutMs: 1500 },
    },
    auth: { type: "none" },
    helpers: { checksum: "none" },
    commands: [
      { id: "power.on", label: "On", kind: "action", transport: "rs232", payload: "POWR1" },
      { id: "power.off", label: "Off", kind: "action", transport: "rs232", payload: "POWR0" },
    ],
    feedback: [],
  },
  "pi-i2c.json": {
    specVersion: "1.0",
    device: { manufacturer: "Raspberry Pi", model: "I2C device", type: "other", notes: "Needs i2cset. Address in auth.address." },
    transports: { local: { kind: "i2c", bus: 1, address: "0x3c", timeoutMs: 1500 } },
    auth: { type: "none", instanceFields: ["address"] },
    helpers: { checksum: "none" },
    commands: [{ id: "power.on", label: "Write 0x01", kind: "action", transport: "rs232", payload: "0x00 0x01" }],
    feedback: [],
  },
  "denon-dn-500av.json": {
    specVersion: "2",
    device: {
      manufacturer: "Denon",
      model: "DN-500AV",
      type: "amplifier",
      notes: "Telnet 23 or RS-232 9600 8N1. Same AVR ASCII as consumer Denon. Source names follow the unit labels (HDMI is assigned to BD/SAT/CBL/etc in the 500AV menu). Volume 00–98.",
    },
    transports: {
      lan: { protocol: "tcp", port: 23, encoding: "ascii", lineEnding: "\r", timeoutMs: 2000 },
      rs232: { baud: 9600, dataBits: 8, parity: "none", stopBits: 1, encoding: "ascii", lineEnding: "\r", timeoutMs: 2000 },
    },
    auth: { type: "none", instanceFields: [] },
    pacing: { minIntervalMs: 200, powerOnDelayMs: 2000 },
    probe: { transport: "lan", payload: "", success: { type: "contains", value: "" } },
    helpers: { checksum: "none" },
    commands: [
      { id: "power.on", label: "Power On", kind: "action", transport: "lan", payload: "PWON" },
      { id: "power.off", label: "Standby", kind: "action", transport: "lan", payload: "PWSTANDBY" },
      { id: "volume.up", label: "Volume Up", kind: "action", transport: "lan", payload: "MVUP" },
      { id: "volume.down", label: "Volume Down", kind: "action", transport: "lan", payload: "MVDOWN" },
      { id: "volume.set", label: "Volume", kind: "range", min: 0, max: 98, step: 1, transport: "lan", payload: "MV{value}" },
      { id: "mute.on", label: "Mute", kind: "action", transport: "lan", payload: "MUON" },
      { id: "mute.off", label: "Unmute", kind: "action", transport: "lan", payload: "MUOFF" },
      { id: "input.bd", label: "Blu-ray", kind: "action", transport: "lan", payload: "SIBD" },
      { id: "input.dvd", label: "DVD", kind: "action", transport: "lan", payload: "SIDVD" },
      { id: "input.sat", label: "SAT / CBL", kind: "action", transport: "lan", payload: "SISAT/CBL" },
      { id: "input.game", label: "Game", kind: "action", transport: "lan", payload: "SIGAME" },
      { id: "input.aux1", label: "AUX 1", kind: "action", transport: "lan", payload: "SIAUX1" },
      { id: "input.aux2", label: "AUX 2", kind: "action", transport: "lan", payload: "SIAUX2" },
      { id: "input.cd", label: "CD", kind: "action", transport: "lan", payload: "SICD" },
      { id: "input.tuner", label: "Tuner", kind: "action", transport: "lan", payload: "SITUNER" },
      { id: "input.net", label: "Network", kind: "action", transport: "lan", payload: "SINET" },
      { id: "input.usb", label: "USB", kind: "action", transport: "lan", payload: "SIUSB" },
      { id: "surround.stereo", label: "Stereo", kind: "action", transport: "lan", payload: "MSSTEREO" },
      { id: "surround.movie", label: "Movie", kind: "action", transport: "lan", payload: "MSMOVIE" },
    ],
    feedback: [
      { id: "power.state", label: "Power", kind: "enum", values: ["off", "on"], transport: "lan", mode: "poll", query: "PW?", pollMs: 4000, parse: { type: "contains", value: "PWON", map: { PWON: "on", PWSTANDBY: "off" } } },
      { id: "volume.level", label: "Volume", kind: "range", min: 0, max: 98, transport: "lan", mode: "poll", query: "MV?", pollMs: 4000, parse: { type: "regex", pattern: "MV([0-9]{2})" } },
      { id: "mute.state", label: "Mute", kind: "enum", values: ["off", "on"], transport: "lan", mode: "poll", query: "MU?", pollMs: 5000, parse: { type: "contains", value: "MUON", map: { MUON: "on", MUOFF: "off" } } },
      { id: "input.current", label: "Input", kind: "string", transport: "lan", mode: "poll", query: "SI?", pollMs: 5000, parse: { type: "regex", pattern: "SI([^\\r]+)" } },
    ],
  },
};
