/** Re-export LAN (venue) Wi‑Fi helpers (Linux nmcli). */
export {
  isWirelessIfaceName,
  isWirelessIface,
  listSysfsNetNames,
  listWirelessIfaceNames,
  normalizeWifiSsid,
  normalizeWifiPsk,
  buildNmcliWifiRescanArgv,
  buildNmcliWifiListArgv,
  buildNmcliWifiConnectArgv,
  scrubWifiSecret,
  parseWifiListOutput,
  resolveLanWifiTarget,
  scanLanWifiViaNmcli,
  applyLanWifiViaNmcli,
  createNmcliRunner,
  classifyNmcliFailure,
  platformGate,
  LAN_WIFI_LINUX_ONLY,
  LAN_WIFI_NMCLI_MISSING,
  LAN_WIFI_SUDOERS,
  LAN_WIFI_LAN_UNSET,
  LAN_WIFI_LAN_MISSING,
  LAN_WIFI_NOT_WIRELESS,
  LAN_WIFI_SSID_REQUIRED,
  LAN_WIFI_PSK_REQUIRED,
  RELAY_LAN_WIFI_CONNECTION_ID,
} from "../../../scripts/lan-wifi.mjs";
