/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as ApiConfigUnlockRouteImport } from './routes/api/config-unlock'
import { Route as ApiPanelUnlockRouteImport } from './routes/api/panel-unlock'
import { Route as ApiPeerRouteImport } from './routes/api/peer'
import { Route as ApiPingRouteImport } from './routes/api/ping'
import { Route as ApiRoomRouteImport } from './routes/api/room'
import { Route as ApiVarsRouteImport } from './routes/api/vars'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConfigUnlockRoute = ApiConfigUnlockRouteImport.update({
  id: '/api/config-unlock',
  path: '/api/config-unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPanelUnlockRoute = ApiPanelUnlockRouteImport.update({
  id: '/api/panel-unlock',
  path: '/api/panel-unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPeerRoute = ApiPeerRouteImport.update({
  id: '/api/peer',
  path: '/api/peer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPingRoute = ApiPingRouteImport.update({
  id: '/api/ping',
  path: '/api/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoomRoute = ApiRoomRouteImport.update({
  id: '/api/room',
  path: '/api/room',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVarsRoute = ApiVarsRouteImport.update({
  id: '/api/vars',
  path: '/api/vars',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/config': typeof ConfigRoute
  '/api/config-unlock': typeof ApiConfigUnlockRoute
  '/api/panel-unlock': typeof ApiPanelUnlockRoute
  '/api/peer': typeof ApiPeerRoute
  '/api/ping': typeof ApiPingRoute
  '/api/room': typeof ApiRoomRoute
  '/api/vars': typeof ApiVarsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/config': typeof ConfigRoute
  '/api/config-unlock': typeof ApiConfigUnlockRoute
  '/api/panel-unlock': typeof ApiPanelUnlockRoute
  '/api/peer': typeof ApiPeerRoute
  '/api/ping': typeof ApiPingRoute
  '/api/room': typeof ApiRoomRoute
  '/api/vars': typeof ApiVarsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/config': typeof ConfigRoute
  '/api/config-unlock': typeof ApiConfigUnlockRoute
  '/api/panel-unlock': typeof ApiPanelUnlockRoute
  '/api/peer': typeof ApiPeerRoute
  '/api/ping': typeof ApiPingRoute
  '/api/room': typeof ApiRoomRoute
  '/api/vars': typeof ApiVarsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/config'
    | '/api/config-unlock'
    | '/api/panel-unlock'
    | '/api/peer'
    | '/api/ping'
    | '/api/room'
    | '/api/vars'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/config'
    | '/api/config-unlock'
    | '/api/panel-unlock'
    | '/api/peer'
    | '/api/ping'
    | '/api/room'
    | '/api/vars'
  id:
    | '__root__'
    | '/'
    | '/config'
    | '/api/config-unlock'
    | '/api/panel-unlock'
    | '/api/peer'
    | '/api/ping'
    | '/api/room'
    | '/api/vars'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfigRoute: typeof ConfigRoute
  ApiConfigUnlockRoute: typeof ApiConfigUnlockRoute
  ApiPanelUnlockRoute: typeof ApiPanelUnlockRoute
  ApiPeerRoute: typeof ApiPeerRoute
  ApiPingRoute: typeof ApiPingRoute
  ApiRoomRoute: typeof ApiRoomRoute
  ApiVarsRoute: typeof ApiVarsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/config-unlock': {
      id: '/api/config-unlock'
      path: '/api/config-unlock'
      fullPath: '/api/config-unlock'
      preLoaderRoute: typeof ApiConfigUnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/panel-unlock': {
      id: '/api/panel-unlock'
      path: '/api/panel-unlock'
      fullPath: '/api/panel-unlock'
      preLoaderRoute: typeof ApiPanelUnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/peer': {
      id: '/api/peer'
      path: '/api/peer'
      fullPath: '/api/peer'
      preLoaderRoute: typeof ApiPeerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ping': {
      id: '/api/ping'
      path: '/api/ping'
      fullPath: '/api/ping'
      preLoaderRoute: typeof ApiPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/room': {
      id: '/api/room'
      path: '/api/room'
      fullPath: '/api/room'
      preLoaderRoute: typeof ApiRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vars': {
      id: '/api/vars'
      path: '/api/vars'
      fullPath: '/api/vars'
      preLoaderRoute: typeof ApiVarsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfigRoute: ConfigRoute,
  ApiConfigUnlockRoute: ApiConfigUnlockRoute,
  ApiPanelUnlockRoute: ApiPanelUnlockRoute,
  ApiPeerRoute: ApiPeerRoute,
  ApiPingRoute: ApiPingRoute,
  ApiRoomRoute: ApiRoomRoute,
  ApiVarsRoute: ApiVarsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
